### PR TITLE
Add float support

### PR DESCRIPTION
**Pull request by pinguinjkeke**
Table and class named "Double" due to new PHP7 class naming rules

### CODE REVIEW

**Comment by IsraelOrtuno** [comment]
MySQL has Float and Double, which one are you really trying to?

**Comment by pinguinjkeke** [comment]
Float. I don't know how to name class. Maybe you should rename all classes like "IntegerValue", "FloatValue" etc

**Comment by pinguinjkeke** [comment]
Should I change that names for something else and create a new pull request? What do you think about class naming?

**Comment by royduin** [comment]
Just change everywhere you've got `double` to `float` then @IsraelOrtuno will accept your pull request I think.

**Comment by pinguinjkeke** [comment]
@royduin PHP7 won't accept Float as a class name. So I'm suggesting to name classes as FloatValue, IntegerValue, etc.

**Comment by IsraelOrtuno** [comment]
I don't like to include prefixes on classes when namespace is explicit
enough but in this case it looks like it's just required. Will get back to
DataValue naming convention.

Anyway gotta say only Float would affect, maybe just naming Float to
FloatNum or something like that let rest untouchable. Do you like that?

On Monday, 9 May 2016, Alexander Avakov notifications@github.com wrote:

> @royduin https://github.com/royduin PHP7 won't accept Float as a class
> name. So I'm suggesting to name classes as FloatValue, IntegerValue, etc.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/IsraelOrtuno/Eavquent/pull/40#issuecomment-217867503

## 

Un saludo
Israel Ortuño

**Comment by pinguinjkeke** [comment]
@IsraelOrtuno it's sounds good too. I support your opinion about namespacing and "Value" postfixes.
On the other hand, it's good when class name mirroring exactly the same SQL-type.

So, "Floatnum"?

**Comment by IsraelOrtuno** [comment]
Despite I like consistency, I will do an exception yep... Floatnum sounds good to me :)

**Comment by IsraelOrtuno** [comment]
@pinguinjkeke why do you close? Just commit on it or are you going to PR again? ;D

**Comment by pinguinjkeke** [comment]
Crap. I have already deleted old fork and ready to PR again. Am I doing bad things?

**Comment by IsraelOrtuno** [comment]
Nah, it's ok, thanks for collaborating :D

**Pull request closed without merging**
